package_rename_config:
  android:
    app_name: Count App
    package_name: com.kingbenny101.countapp

  windows:
    app_name: Count App
    organization: KingBenny101
    copyright_notice: Â© 2025 KingBenny101. All rights reserved.
    exe_name: countapp
